---

AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 bucket with non-public access
Parameters:
  BucketNameParameter:
      Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameParameter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true